const initialState = {
  user: {},
  playing: {},
  search: [],
  favorites: [],
  female: [
    {
      id: 1,
      name: 'Sammy Fontalvo',
      position: 'Defensa',
      height: 1.61,
      cover: 'http://dummyimage.com/800x600.png/001f3f/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 2,
      name: 'Melissa Humana',
      position: 'Defensa',
      height: 1.75,
      cover: 'http://dummyimage.com/800x600.png/0074D9/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 3,
      name: 'Sarah Pavan',
      position: 'Bloque',
      height: 1.98,
      cover: 'http://dummyimage.com/800x600.png/7FDBFF/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 4,
      name: 'Laura Ludwig',
      position: 'Defensa',
      height: 1.81,
      cover: 'http://dummyimage.com/800x600.png/39CCCC/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 5,
      name: 'Kira Walkenhorst',
      position: 'Bloque',
      height: 1.84,
      cover: 'http://dummyimage.com/800x600.png/3D9970/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
  ],
  male: [
    {
      id: 10,
      name: 'Juango Murillo',
      position: 'Bloque',
      height: 1.82,
      cover: 'http://dummyimage.com/800x600.png/FF4136/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 11,
      name: 'Adrian Carambula',
      position: 'Defensa',
      height: 1.83,
      cover: 'http://dummyimage.com/800x600.png/85144B/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 12,
      name: 'Alex Ranghieri',
      position: 'Bloque',
      height: 2.0,
      cover: 'http://dummyimage.com/800x600.png/F012BE/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 13,
      name: 'Taylor Crabb',
      position: 'Defensa',
      height: 1.83,
      cover: 'http://dummyimage.com/800x600.png/B10DC9/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 14,
      name: 'Jake Gibb',
      position: 'Bloque',
      height: 2.01,
      cover: 'http://dummyimage.com/800x600.png/111111/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
  ],
};

export default initialState;
