const initialState = {
  user: {},
  playing: {},
  favorites: [],
  search: [],
  female: [
    {
      id: 1,
      name: 'Sammy Fontalvo',
      position: 'Defensa',
      height: 1.61,
      cover: 'http://dummyimage.com/800x600.png/001f3f/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 2,
      name: 'Melissa Humana',
      position: 'Defensa',
      height: 1.75,
      cover: 'http://dummyimage.com/800x600.png/0074D9/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 3,
      name: 'Sarah Pavan',
      position: 'Bloque',
      height: 1.98,
      cover: 'http://dummyimage.com/800x600.png/7FDBFF/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 4,
      name: 'Laura Ludwig',
      position: 'Defensa',
      height: 1.81,
      cover: 'http://dummyimage.com/800x600.png/39CCCC/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 5,
      name: 'Kira Walkenhorst',
      position: 'Bloque',
      height: 1.84,
      cover: 'http://dummyimage.com/800x600.png/3D9970/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 6,
      name: 'Kerri Walsh',
      position: 'Bloque',
      height: 1.88,
      cover: 'http://dummyimage.com/800x600.png/2ECC40/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 7,
      name: 'Misty May',
      position: 'Defensa',
      height: 1.82,
      cover: 'http://dummyimage.com/800x600.png/01FF70/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 8,
      name: 'April Ross',
      position: 'Bloque',
      height: 1.85,
      cover: 'http://dummyimage.com/800x600.png/FFDC00/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
    {
      id: 9,
      name: 'Jennifer Kessy',
      position: 'Defensa',
      height: 1.8,
      cover: 'http://dummyimage.com/800x600.png/FF851B/ffffff',
      saque: 5,
      rece: 8,
      levante: 9,
      ataque: 7,
      bloque: 3,
      defensa: 10,
    },
  ],
  male: [
    {
      id: 10,
      name: 'Juango Murillo',
      position: 'Bloque',
      height: 1.82,
      cover: 'http://dummyimage.com/800x600.png/FF4136/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 11,
      name: 'Adrian Carambula',
      position: 'Defensa',
      height: 1.83,
      cover: 'http://dummyimage.com/800x600.png/85144B/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 12,
      name: 'Alex Ranghieri',
      position: 'Bloque',
      height: 2.0,
      cover: 'http://dummyimage.com/800x600.png/F012BE/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 13,
      name: 'Taylor Crabb',
      position: 'Defensa',
      height: 1.83,
      cover: 'http://dummyimage.com/800x600.png/B10DC9/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 14,
      name: 'Jake Gibb',
      position: 'Bloque',
      height: 2.01,
      cover: 'http://dummyimage.com/800x600.png/111111/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 15,
      name: 'Anders Mol',
      position: 'Bloque',
      height: 2.0,
      cover: 'http://dummyimage.com/800x600.png/AAAAAA/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 16,
      name: 'Christian Sorum',
      position: 'Defensa',
      height: 1.92,
      cover: 'http://dummyimage.com/800x600.png/DDDDDD/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 17,
      name: 'Phil Dalhausser',
      position: 'Bloque',
      height: 2.05,
      cover: 'http://dummyimage.com/800x600.png/789ABC/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
    {
      id: 18,
      name: 'Todd Rogers',
      position: 'Defensa',
      height: 1.87,
      cover: 'http://dummyimage.com/800x600.png/CBA987/ffffff',
      saque: 5,
      rece: 7,
      levante: 3,
      ataque: 10,
      bloque: 10,
      defensa: 8,
    },
  ],
};

export default initialState;
